
import Header from "@/app/Common/Header"
import { fetchProductDetails } from "@/app/data/ProductDetails";

export const metadata = {
  title: 'AM Relatix Sub Categories',
  description: 'Generated by create next app',
}
export async function getdata(value) {
  const data = await fetchProductDetails(value);
  return {
    data,
  };
}
export default async function ProductDetailsLayout({ children,params }) {
  const { data } = await getdata(params.slug);
  return (
      <div>
        <Header params={data}/>
        {children}
      </div>
  )
}
