import Header from "@/app/Common/Header"
import NormalCategoriesbar from "@/app/Common/NormalCategoriesbar"
import { fetchSubCategories } from "@/app/data/SubCategories"

export const metadata = {
  title: 'AM Relatix Normal Categories',
  description: 'Generated by create next app',
}
export async function getdata(value) {
  const data = await fetchSubCategories(value);
  return {
    data,
  };
}
export default async function NormalCategoriesLayout({ children,params}) {
  const { data } = await getdata(params.slug);
   let length =data?.normalCategoriesList?.length + data?.level3CategoriesList?.length
  return (
      <div>
        <Header params={data}/>
        <NormalCategoriesbar value={data?.normalCategoriesList} level3Categories={data?.level3CategoriesList} length={length}/>
        {children}
      </div>
  )
}