import './globals.css';
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import NewComparison from './Common/NewComparison';
import Footer from './Common/Footer';
export const metadata = {
  title: 'AM Relatix',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        {/* <NewComparison/> */}
        <Footer/>
      </body>
    </html>
  )
}
